version: "3"
services:
  server:
    container_name: grpc-demo-server
    image: mchiu2006/grpc-demo-server
    build:
      context: .
      dockerfile: ./Dockerfile
      target: server
  proxy:
    container_name: grpc-envoy-proxy
    image: mchiu2006/grpc-envoy-proxy
    build:
      context: .
      dockerfile: ./Dockerfile
      target: proxy
    ports:
      - 8070:8070
      - 9901:9901
