[project]
name = "grpc-stream-sample"
version = "0.1.0"
description = "a simple gRPC demo using python"
authors = ["TATA <evadcmd@gmail.com>"]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "grpcio>=1.80.0",
    "grpcio-tools>=1.80.0",
    "mypy-protobuf>=5.0.0",
]

[tool.pyright]
extraPaths = ["src"]
exclude = [
  "**/node_modules",
  "**/__pycache__",
  "**/.*",
  ".venv",
  "src/schema/**"
]
reportAttributeAccessIssue = "warning"