# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'example.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x07\x65xample\"(\n\x05Param\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01z\x18\x03 \x01(\x05\"\x14\n\x03Res\x12\r\n\x05value\x18\x01 \x01(\x05\x32\xbf\x01\n\x04\x46unc\x12(\n\x06Simple\x12\x0e.example.Param\x1a\x0c.example.Res\"\x00\x12.\n\nStreamResp\x12\x0e.example.Param\x1a\x0c.example.Res\"\x00\x30\x01\x12-\n\tStreamReq\x12\x0e.example.Param\x1a\x0c.example.Res\"\x00(\x01\x12.\n\x08\x42iStream\x12\x0e.example.Param\x1a\x0c.example.Res\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARAM']._serialized_start=26
  _globals['_PARAM']._serialized_end=66
  _globals['_RES']._serialized_start=68
  _globals['_RES']._serialized_end=88
  _globals['_FUNC']._serialized_start=91
  _globals['_FUNC']._serialized_end=282
# @@protoc_insertion_point(module_scope)
