# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_src.example_pb2 as example__pb2


class FuncStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Simple = channel.unary_unary(
                '/example.Func/Simple',
                request_serializer=example__pb2.Param.SerializeToString,
                response_deserializer=example__pb2.Res.FromString,
                )
        self.StreamResp = channel.unary_stream(
                '/example.Func/StreamResp',
                request_serializer=example__pb2.Param.SerializeToString,
                response_deserializer=example__pb2.Res.FromString,
                )
        self.StreamReq = channel.stream_unary(
                '/example.Func/StreamReq',
                request_serializer=example__pb2.Param.SerializeToString,
                response_deserializer=example__pb2.Res.FromString,
                )
        self.BiStream = channel.stream_stream(
                '/example.Func/BiStream',
                request_serializer=example__pb2.Param.SerializeToString,
                response_deserializer=example__pb2.Res.FromString,
                )


class FuncServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Simple(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamResp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamReq(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BiStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FuncServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Simple': grpc.unary_unary_rpc_method_handler(
                    servicer.Simple,
                    request_deserializer=example__pb2.Param.FromString,
                    response_serializer=example__pb2.Res.SerializeToString,
            ),
            'StreamResp': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamResp,
                    request_deserializer=example__pb2.Param.FromString,
                    response_serializer=example__pb2.Res.SerializeToString,
            ),
            'StreamReq': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamReq,
                    request_deserializer=example__pb2.Param.FromString,
                    response_serializer=example__pb2.Res.SerializeToString,
            ),
            'BiStream': grpc.stream_stream_rpc_method_handler(
                    servicer.BiStream,
                    request_deserializer=example__pb2.Param.FromString,
                    response_serializer=example__pb2.Res.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example.Func', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Func(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Simple(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.Func/Simple',
            example__pb2.Param.SerializeToString,
            example__pb2.Res.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamResp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/example.Func/StreamResp',
            example__pb2.Param.SerializeToString,
            example__pb2.Res.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamReq(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/example.Func/StreamReq',
            example__pb2.Param.SerializeToString,
            example__pb2.Res.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BiStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/example.Func/BiStream',
            example__pb2.Param.SerializeToString,
            example__pb2.Res.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
