# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'schema/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14schema/service.proto\"(\n\x05Param\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01z\x18\x03 \x01(\x05\"\x14\n\x03Res\x12\r\n\x05value\x18\x01 \x01(\x05\x32\x7f\n\x04\x46unc\x12\x18\n\x06Simple\x12\x06.Param\x1a\x04.Res\"\x00\x12\x1e\n\nStreamResp\x12\x06.Param\x1a\x04.Res\"\x00\x30\x01\x12\x1d\n\tStreamReq\x12\x06.Param\x1a\x04.Res\"\x00(\x01\x12\x1e\n\x08\x42iStream\x12\x06.Param\x1a\x04.Res\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARAM']._serialized_start=24
  _globals['_PARAM']._serialized_end=64
  _globals['_RES']._serialized_start=66
  _globals['_RES']._serialized_end=86
  _globals['_FUNC']._serialized_start=88
  _globals['_FUNC']._serialized_end=215
# @@protoc_insertion_point(module_scope)
