"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from schema import service_pb2 as _service_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class FuncStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> FuncAsyncStub: ...
    Simple: _grpc.UnaryUnaryMultiCallable[_service_pb2.Param, _service_pb2.Res]
    StreamResp: _grpc.UnaryStreamMultiCallable[_service_pb2.Param, _service_pb2.Res]
    StreamReq: _grpc.StreamUnaryMultiCallable[_service_pb2.Param, _service_pb2.Res]
    BiStream: _grpc.StreamStreamMultiCallable[_service_pb2.Param, _service_pb2.Res]

@_typing.type_check_only
class FuncAsyncStub(FuncStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    Simple: _aio.UnaryUnaryMultiCallable[_service_pb2.Param, _service_pb2.Res]  # type: ignore[assignment]
    StreamResp: _aio.UnaryStreamMultiCallable[_service_pb2.Param, _service_pb2.Res]  # type: ignore[assignment]
    StreamReq: _aio.StreamUnaryMultiCallable[_service_pb2.Param, _service_pb2.Res]  # type: ignore[assignment]
    BiStream: _aio.StreamStreamMultiCallable[_service_pb2.Param, _service_pb2.Res]  # type: ignore[assignment]

class FuncServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def Simple(
        self,
        request: _service_pb2.Param,
        context: _ServicerContext,
    ) -> _typing.Union[_service_pb2.Res, _abc.Awaitable[_service_pb2.Res]]: ...

    @_abc_1.abstractmethod
    def StreamResp(
        self,
        request: _service_pb2.Param,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_service_pb2.Res], _abc.AsyncIterator[_service_pb2.Res]]: ...

    @_abc_1.abstractmethod
    def StreamReq(
        self,
        request_iterator: _MaybeAsyncIterator[_service_pb2.Param],
        context: _ServicerContext,
    ) -> _typing.Union[_service_pb2.Res, _abc.Awaitable[_service_pb2.Res]]: ...

    @_abc_1.abstractmethod
    def BiStream(
        self,
        request_iterator: _MaybeAsyncIterator[_service_pb2.Param],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_service_pb2.Res], _abc.AsyncIterator[_service_pb2.Res]]: ...

def add_FuncServicer_to_server(servicer: FuncServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
